export const ACTIONS = {
    ERROR: 'ERROR',
    PHENOMENONDATA: 'PHENOMENONDATA',
    GET_RADAR: 'GET_RADAR',
    UPDATE_STATUS: 'UPDATE_STATUS',
    HIDDENPHENOMENARATING: 'HIDDENPHENOMENARATING',
    HIDDENPHENOMENAVOTING: 'HIDDENPHENOMENAVOTING',
    RADAR: 'RADAR',
    ISFLIP: 'ISFLIP',
    MODE: 'MODE',
    AVGMEDIAN: 'AVGMEDIAN'
}